### PR TITLE
comment : added comment

### PR DESCRIPTION
**Pull request by Ansonsd5**

### CODE REVIEW

**Review by jsuryakt — COMMENTED** [review]
In createOrder we're not using cart obj anywhere

**Review by jsuryakt — COMMENTED** [review]
proceedToPayment - orderId

**Review by jsuryakt — COMMENTED** [review]
proceedPaymentPromise*

**Review by jsuryakt — COMMENTED** [review]
In showOrderSummary we can make const orderDetails=res.orderDetails

And then get transactionId as orderDetails.transactionId and totalCost as orderDetails.totalCost

**Review by jsuryakt — COMMENTED** [review]
In updateWallet if the amount is less than the wallet we don't do anything and promise will be pending. I suggest we should check it this way, first check if amount exists and then check if wallet is less than amount if yes then reject saying that low balance else you can subtract and resolve

**Comment by Ansonsd5** [comment]
> In createOrder we're not using cart obj anywhere
 checking if cart not exists then it will reject

**Pull request merged**
